spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nebula?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
    username: username
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    drive-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
  main:
    allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.nebula
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl