export const labelMapping = {
    label: '标签',
    tag: '标签类型',
    placeholder: '占位符',
    disabled: '禁用',
    modelValue: '绑定值',
    'allow-clear': '允许清除',
    "prefix-icon": '前缀图标',
    "suffix-icon": '后缀图标',
    password: '密码',
    size: '尺寸',
    maxlength: '最大长度',
    'show-count': '显示字符数',
    'v-model': '绑定值',
    disabledInput: '禁止输入',
    step: '步数',
    'step-strictly': '必须为步数的倍数',
    position: '控制器位置',
    precision: '精度(小数位数)',
    min: '最小值',
    max: '最大值',
    indicator: '后缀标识',
    allowClear: '允许清空',
    multiple: '允许多选',
    showSearch: '允许搜索',
    searchPlaceholder: '搜索占位符',
    "onswitch-text": "选中描述",
    "unswitch-text": "未选中描述",
    "onswitch-value": "选中值",
    "unswitch-value": "未选中值",
    vertical:'垂直显示',
    range:'选择区间',
    type:'类型',
    simple:'无需点击确认',
    timestamp:'时间戳模式',
    format:'格式',
    length:'长度',
    readonly:'只读模式',
    theme:'主题颜色',
    half:'允许半星',
    text:'显示文本',
    preset:'预设',
    page:'开启分页',
    url:'上传地址',
    data:'附带参数',
    header:'请求头',
    acceptMime:'允许类型',
    auto:'自动上传',
    field:'文件名',
    drag:'拖拽上传',
    cut:'允许裁剪',
    dragText:"拖拽文本",
    fluid:'全屏',
    radius:'圆角',
    border:'边框',
    "border-style":"边框类型",
    loading:"加载",
    decollator:"分隔符号",
    onlyLastLevel:"只显示最后一级",
    skin:"皮肤",
    options:"选项"
};